task = "simple_math"
version = "1.0"

[data]
source = "huggingface"
dataset_path = "gsm8k"
subset = "main"
split = "test"
limit = 100

[preprocessing]
question_template = "Solve this math problem: {question}\n\nAnswer with just the numerical result."
ground_truth_field = "answer"
input_field = "question"

[[metrics]]
name = "exact_match"
weight = 1.0

[[metrics]]
name = "within_1_percent"
weight = 0.8

[metadata]
description = "Simple math problems for testing TOML configuration"
domain = "mathematics"
task_type = "numerical_reasoning"
toml_example = true