name: PeptideFox
options:
  bundleIdPrefix: com.peptidefox
targets:
  PeptideFox:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [PeptideFox]
    settings:
      INFOPLIST_FILE: PeptideFox/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.peptidefox.app
      SWIFT_VERSION: "5.0"
      DEVELOPMENT_TEAM: ""
